STR_C_CONTIGUOUS = "C_CONTIGUOUS"
# core forest vegetation simulator attribute names
STR_MAXCYCLES = "maxcycles"
STR_MAXPLOTS = "maxplots"
STR_MAXSPECIES = "maxspecies"
STR_MAXTREES = "maxtrees"
STR_NCYCLES = "ncycles"
STR_NPLOTS = "nplots"
STR_NTREES = "ntrees"
# stand visualization system attribute names
STR_NSVSOBJS = "nsvsobjs"
STR_NDEADOBJS = "ndeadobjs"
STR_NCWDOBJS = "ncwdobjs"
STR_MXSVSOBJS = "mxsvsobjs"
STR_MXDEADOBJS = "mxdeadobjs"
STR_MXCWDOBJS = "mxcwdobjs"
STR_NOBJS = "nobjs"

STAND_CN_COLUMN_NAME = "stand_cn"
STAND_ID_COLUMN_NAME = "stand_id"
MGMT_ID_COLUMN_NAME = "mgmt_id"

NEEDED_ROUTINES = (
    "fvs",
    "fvsAddActivity",
    "fvsAddTrees",
    "fvsDimSizes",
    "fvsEvmonAttr",
    "fvsFFEAttrs",
    "fvsGetRestartCode",
    "fvsGetRtnCode",
    "fvsGetICCode",
    "fvsSVSDimSizes",
    "fvsSetStoppointCodes",
    "fvsSetCmdLine",
    "fvsSVSObjData",
    "fvsSpeciesAttr",
    "fvsSpeciesCode",
    "fvsStandID",
    "fvsSummary",
    "fvsTreeAttr",
    "fvsUnitConversion",
)

SPECIES_INDEX_COLUMN_NAME = "fvs_index"
SPECIES_ALPHA_COLUMN_NAME = "fvs_alpha"
SPECIES_FIA_COLUMN_NAME = "fia"
SPECIES_PLANTS_COLUMN_NAME = "plants"
SPECIES_COLUMN_NAMES = [
    SPECIES_INDEX_COLUMN_NAME,
    SPECIES_ALPHA_COLUMN_NAME,
    SPECIES_FIA_COLUMN_NAME,
    SPECIES_PLANTS_COLUMN_NAME,
]
ADD_TREES_COLS = (
    "dbh",
    "species",
    "ht",
    "cratio",
    "plot",
    "tpa",
)

TREE_ATTRS = (
    "age",
    "bapctile",
    "bdft",
    "cratio",
    "crownwt0",
    "crownwt1",
    "crownwt2",
    "crownwt3",
    "crownwt4",
    "crownwt5",
    "crwdth",
    "dbh",
    "defect",
    "dg",
    "ht",
    "htg",
    "id",
    "mcuft",
    "mgmtcd",
    "mort",
    "plot",
    "plotsize",
    "ptbalt",
    "scuft",
    "special",
    "species",
    "tcuft",
    "tpa",
)

SPECIES_ATTRS = (
    "baimult",
    "bfmeth",
    "bfmind",
    "bfstmp",
    "bftopd",
    "frmcls",
    "htgmult",
    "maxdbh",
    "maxdbhcd",
    "maxht",
    "mcmeth",
    "mcmind",
    "mcstmp",
    "mctopd",
    "minmort",
    "mortdia1",
    "mortdia2",
    "mortmult",
    "regdmult",
    "reghmult",
    "spccf",
    "spsdi",
    "spsiteindx",
)

FFE_FALLYRS_ATTRS = (
    "fallyrs0",
    "fallyrs1",
    "fallyrs2",
    "fallyrs3",
    "fallyrs4",
    "fallyrs5",
)

# ``fvsSVSObjData`` (live 3D objects, standing dead snags, and coarse
# woody debris). Length of each array is the corresponding current
# count from ``fvsSVSDimSizes``.
SVS_LIVE_OBJ_ATTRS = (
    "objtype",
    "objindex",
    "xloc",
    "yloc",
)
SVS_SNAG_OBJ_ATTRS = (
    "snagdbh",
    "snaglen",
    "snagyear",
    "snagspp",
    "snagfdir",
    "snagstat",
    "snagwt0",
    "snagwt1",
    "snagwt2",
    "snagwt3",
)
SVS_CWD_OBJ_ATTRS = (
    "cwddia",
    "cwdlen",
    "cwdpil",
    "cwddir",
    "cwdwt",
)
SVS_OBJ_ATTRS: tuple[str, ...] = (
    SVS_LIVE_OBJ_ATTRS + SVS_SNAG_OBJ_ATTRS + SVS_CWD_OBJ_ATTRS
)

EVMON_ATTRS = (
    "aabvbio",
    "aabvcrb",
    "aadbh",
    "aba",
    "abdft",
    "acancov",
    "acc",
    "accf",
    "adbhwtba",
    "afolbio",
    "afolcrb",
    "age",
    "agecmp",
    "ahtwtba",
    "amaxhs",
    "amcuft",
    "amerbio",
    "amercrb",
    "aminhs",
    "anumss",
    "arden",
    "arden2",
    "asawbio",
    "asawcrb",
    "asclass",
    "ascuft",
    "asdi",
    "asdi2",
    "asdimax",
    "aspect",
    "astrdbh",
    "atcuft",
    "atopht",
    "atpa",
    "babvbio",
    "babvcrb",
    "badbh",
    "bba",
    "bbdft",
    "bcancov",
    "bccf",
    "bdbhwtba",
    "bfolbio",
    "bfolcrb",
    "bmaxhs",
    "bmcuft",
    "bmerbio",
    "bmercrb",
    "bminhs",
    "bnumss",
    "brden",
    "brden2",
    "bsawbio",
    "bsawcrb",
    "bsclass",
    "bscuft",
    "bsdi",
    "bsdi2",
    "bsdimax",
    "bstrdbh",
    "btcuft",
    "btopht",
    "btpa",
    "bw%stnd",
    "cendyear",
    "county",
    "crbaseht",
    "crbulkdn",
    "crownidx",
    "cut",
    "cycle",
    "dba",
    "dba%",
    "dccf",
    "dccf%",
    "disccost",
    "discrate",
    "discrevn",
    "dtpa",
    "dtpa%",
    "ecbdft",
    "ecbdft",
    "eccuft",
    "eccuft",
    "elev",
    "evphase",
    "fire",
    "fireyear",
    "fisherin",
    "forstval",
    "fortyp",
    "habtype",
    "harvcost",
    "harvrevn",
    "herbwt",
    "invyear",
    "irr",
    "lat",
    "long",
    "mai",
    "minsoil",
    "mort",
    "mpbprob",
    "mpbtpak",
    "no",
    "numtrees",
    "pai",
    "pctcost",
    "pnv",
    "propstk",
    "rabvbio",
    "rabvcrb",
    "rbdft",
    "rfolbio",
    "rfolcrb",
    "rmcuft",
    "rmerbio",
    "rmercrb",
    "rprodval",
    "rsawbio",
    "rsawcrb",
    "rscuft",
    "rtcuft",
    "rtpa",
    "sampwt",
    "sev",
    "shrubwt",
    "silvahft",
    "site",
    "sizcls",
    "slope",
    "smr",
    "state",
    "stkcls",
    "tm%df",
    "tm%gf",
    "tm%stnd",
    "torchidx",
    "undiscst",
    "undisrvn",
    "year",
    "yes",
)

SUMMARY_COLS = (
    "year",
    "age",
    "tpa",
    "tcuft",
    "mcuft",
    "bdft",
    "rtpa",
    "rtcuft",
    "rmcuft",
    "rbdft",
    "atba",
    "atccf",
    "attopht",
    "prdlen",
    "acc",
    "mort",
    "sampwt",
    "fortyp",
    "sizecls",
    "stkcls",
)
