name: Pytest with Docker

on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t testing -f fvs2py/tests/Dockerfile .

      - name: Run tests in Docker container
        run: docker run testing