name: Pytest with Docker

on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: david.danieldiaz/fvs2py:FS2024.4
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: /code
    - name: Install pytest
      run: pip install pytest
    
    - name: Run tests inside container
      run: pytest /code/fvs2py